data_pathname: data
dream_manager_data_filename: dream_manager_data
hh_color: purple

color_mapper:
  red: 0
  pink: 2
  orange: 3
  yellow: 4
  lime: 5
  green: 6
  teal: 7
  blue: 8
  indigo: 9
  grey: 10
  purple: -1

