# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/custom_chart_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.titleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout.addWidget(self.titleEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tags = QtWidgets.QGroupBox(self.centralwidget)
        self.tags.setObjectName("tags")
        self.tagsBoxLayout = QtWidgets.QVBoxLayout(self.tags)
        self.tagsBoxLayout.setObjectName("tagsBoxLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addTagButton = QtWidgets.QPushButton(self.tags)
        self.addTagButton.setObjectName("addTagButton")
        self.horizontalLayout_2.addWidget(self.addTagButton)
        self.label_2 = QtWidgets.QLabel(self.tags)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.categoriesComboBox = QtWidgets.QComboBox(self.tags)
        self.categoriesComboBox.setObjectName("categoriesComboBox")
        self.horizontalLayout_2.addWidget(self.categoriesComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.deleteAll = QtWidgets.QPushButton(self.tags)
        self.deleteAll.setObjectName("deleteAll")
        self.horizontalLayout_2.addWidget(self.deleteAll)
        self.tagsBoxLayout.addLayout(self.horizontalLayout_2)
        self.tagsScroll = QtWidgets.QScrollArea(self.tags)
        self.tagsScroll.setWidgetResizable(True)
        self.tagsScroll.setObjectName("tagsScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 736, 533))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tagsLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.tagsLayout.setObjectName("tagsLayout")
        self.tagsScroll.setWidget(self.scrollAreaWidgetContents)
        self.tagsBoxLayout.addWidget(self.tagsScroll)
        self.groupBox = QtWidgets.QGroupBox(self.tags)
        self.groupBox.setObjectName("groupBox")
        self.previewLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.previewLayout.setObjectName("previewLayout")
        self.tagsBoxLayout.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.tags)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Titre"))
        self.tags.setTitle(_translate("MainWindow", "Tags"))
        self.addTagButton.setText(_translate("MainWindow", "Ajouter"))
        self.label_2.setText(_translate("MainWindow", "Ajouter à partir d\'une catégorie"))
        self.deleteAll.setText(_translate("MainWindow", "Tout supprimer"))
        self.groupBox.setTitle(_translate("MainWindow", "Prévisualisation"))
        self.saveButton.setText(_translate("MainWindow", "Sauvegarder"))
