from tests.collections.test_base_collection import TestBaseCollection
from tests.collections.test_tags_collection import TestTagsCollection
from tests.collections.test_unique_list import TestUniqueList
