# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 731, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.last_file_loaded_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.last_file_loaded_value.setObjectName("last_file_loaded_value")
        self.horizontalLayout.addWidget(self.last_file_loaded_value)
        self.last_file_loaded_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.last_file_loaded_label.setObjectName("last_file_loaded_label")
        self.horizontalLayout.addWidget(self.last_file_loaded_label)
        self.import_json_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.import_json_button.setObjectName("import_json_button")
        self.horizontalLayout.addWidget(self.import_json_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.last_file_loaded_value.setText(_translate("MainWindow", "Date du dernier fichier chargé : "))
        self.last_file_loaded_label.setText(_translate("MainWindow", "Aucun fichier chargé"))
        self.import_json_button.setText(_translate("MainWindow", "Importer un fichier JSON"))
