# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Esteban\Desktop\Code\DreamsAnalyzer\ui\new_template_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lucidityButton = QtWidgets.QPushButton(self.groupBox)
        self.lucidityButton.setObjectName("lucidityButton")
        self.gridLayout.addWidget(self.lucidityButton, 1, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.groupBox)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 0, 2, 1, 1)
        self.titleButton = QtWidgets.QPushButton(self.groupBox)
        self.titleButton.setObjectName("titleButton")
        self.gridLayout.addWidget(self.titleButton, 0, 1, 1, 1)
        self.tagsButton = QtWidgets.QPushButton(self.groupBox)
        self.tagsButton.setObjectName("tagsButton")
        self.gridLayout.addWidget(self.tagsButton, 1, 0, 1, 1)
        self.moodButton = QtWidgets.QPushButton(self.groupBox)
        self.moodButton.setObjectName("moodButton")
        self.gridLayout.addWidget(self.moodButton, 1, 2, 1, 1)
        self.typeButton = QtWidgets.QPushButton(self.groupBox)
        self.typeButton.setObjectName("typeButton")
        self.gridLayout.addWidget(self.typeButton, 0, 0, 1, 1)
        self.timeButton = QtWidgets.QPushButton(self.groupBox)
        self.timeButton.setObjectName("timeButton")
        self.gridLayout.addWidget(self.timeButton, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 390))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newTemplateTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.newTemplateTextEdit.setObjectName("newTemplateTextEdit")
        self.verticalLayout_2.addWidget(self.newTemplateTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.saveTemplateButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveTemplateButton.setObjectName("saveTemplateButton")
        self.verticalLayout.addWidget(self.saveTemplateButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Editeur"))
        self.lucidityButton.setText(_translate("MainWindow", "Lucidité"))
        self.clearButton.setText(_translate("MainWindow", "Clareté"))
        self.titleButton.setText(_translate("MainWindow", "Titre"))
        self.tagsButton.setText(_translate("MainWindow", "Tags"))
        self.moodButton.setText(_translate("MainWindow", "Mood"))
        self.typeButton.setText(_translate("MainWindow", "Type"))
        self.timeButton.setText(_translate("MainWindow", "Heure"))
        self.saveTemplateButton.setText(_translate("MainWindow", "Sauvegarder"))
